name = "sut"
description = ""
version = "0.1.0"

authors = ["Lionel Draghi"]
maintainers = ["Lionel Draghi <lionel.draghi@free.fr>"]
maintainers-logins = ["LionelDraghi"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["sut"]

[configuration]
generate_C   = false
generate_Ada = false

